from __future__ import annotations

COMPETITIONS: dict[str, dict] = {
    "ERCC": {
        "slug": "champions-cup",
        "name": "Champions Cup",
        "csv": "data/import/champions-cup-matches.csv",
        "defensive_bonus_limit": 7,
    },
    "ERCH": {
        "slug": "challenge-cup",
        "name": "Challenge Cup",
        "csv": "data/import/challenge-cup-matches.csv",
        "defensive_bonus_limit": 7,
    },
    "URC": {
        "slug": "urc",
        "name": "United Rugby Championship",
        "csv": "data/import/urc-matches.csv",
        "defensive_bonus_limit": 7,
    },
    "PREM": {
        "slug": "premiership",
        "name": "Premiership",
        "csv": "data/import/premiership-matches.csv",
        "defensive_bonus_limit": 7,
    },
    "INT": {
        "slug": "test-matchs",
        "name": "Tests internationaux",
        "csv": "data/import/international-matches.csv",
        "defensive_bonus_limit": 7,
    },
}

TEAMS: dict[str, list[tuple[str, str, str]]] = {
    "ERCC": [
        ("ASM Clermont Auvergne", "ASM", "Clermont"),
        ("Glasgow Warriors", "GLA", "Glasgow"),
        ("Leicester Tigers", "LEIC", "Leicester"),
        ("Leinster", "LEI", "Dublin"),
        ("Section Paloise", "PAU", "Pau"),
        ("Sale Sharks", "SAL", "Sale"),
        ("Connacht", "CON", "Galway"),
        ("Exeter Chiefs", "EXE", "Exeter"),
        ("Stade Rochelais", "LAR", "La Rochelle"),
        ("Lions", "LIO", "Johannesburg"),
        ("Saracens", "SAR", "London"),
        ("Stade Toulousain", "TOU", "Toulouse"),
        ("Union Bordeaux Begles", "UBB", "Bordeaux"),
        ("Bristol Bears", "BRS", "Bristol"),
        ("Gloucester Rugby", "GLO", "Gloucester"),
        ("Munster", "MUN", "Cork"),
        ("Racing 92", "RAC", "Paris"),
        ("Stormers", "STO", "Cape Town"),
        ("Bath Rugby", "BAT", "Bath"),
        ("Bulls", "BUL", "Pretoria"),
        ("Cardiff Rugby", "CDF", "Cardiff"),
        ("Montpellier Herault Rugby", "MHR", "Montpellier"),
        ("Northampton Saints", "NOR", "Northampton"),
        ("Stade Francais Paris", "SFP", "Paris"),
    ],
    "ERCH": [
        ("Aviron Bayonnais", "BAY", "Bayonne"),
        ("Cheetahs", "CHE", "Bloemfontein"),
        ("Dragons", "DRA", "Newport"),
        ("USA Perpignan", "USAP", "Perpignan"),
        ("Ulster", "ULS", "Belfast"),
        ("Zebre Parma", "ZEB", "Parma"),
        ("Castres Olympique", "CAS", "Castres"),
        ("LOU Rugby", "LOU", "Lyon"),
        ("Newcastle Falcons", "NEW", "Newcastle"),
        ("Scarlets", "SCA", "Llanelli"),
        ("Sharks", "SHA", "Durban"),
        ("Benetton Treviso", "TRE", "Treviso"),
        ("Black Lion", "BLA", "Tbilisi"),
        ("Edinburgh Rugby", "EDI", "Edinburgh"),
        ("Harlequins", "HAR", "London"),
        ("Ospreys", "OSP", "Swansea"),
        ("RC Toulonnais", "TOL", "Toulon"),
        ("RC Vannes", "VAN", "Vannes"),
    ],
    "URC": [
        ("Bulls", "BUL", "Pretoria"),
        ("Sharks", "SHA", "Durban"),
        ("Stormers", "STO", "Cape Town"),
        ("Glasgow Warriors", "GLA", "Glasgow"),
        ("Edinburgh Rugby", "EDI", "Edinburgh"),
        ("Cardiff Rugby", "CDF", "Cardiff"),
        ("Lions", "LIO", "Johannesburg"),
        ("Dragons", "DRA", "Newport"),
        ("Benetton Treviso", "TRE", "Treviso"),
        ("Leinster", "LEI", "Dublin"),
        ("Ulster", "ULS", "Belfast"),
        ("Munster", "MUN", "Cork"),
        ("Scarlets", "SCA", "Llanelli"),
        ("Ospreys", "OSP", "Swansea"),
        ("Connacht", "CON", "Galway"),
        ("Zebre Parma", "ZEB", "Parma"),
    ],
    "PREM": [
        ("Northampton Saints", "NOR", "Northampton"),
        ("Gloucester Rugby", "GLO", "Gloucester"),
        ("Bath Rugby", "BAT", "Bath"),
        ("Bristol Bears", "BRS", "Bristol"),
        ("Saracens", "SAR", "London"),
        ("Leicester Tigers", "LEIC", "Leicester"),
        ("Exeter Chiefs", "EXE", "Exeter"),
        ("Newcastle Falcons", "NEW", "Newcastle"),
        ("Sale Sharks", "SAL", "Sale"),
        ("Harlequins", "HAR", "London"),
    ],
    "INT": [
        ("Afrique du Sud", "RSA", "Afrique du Sud"),
        ("Afrique du Sud A", "RSA2", "Afrique du Sud"),
        ("All Blacks", "NZL", "Nouvelle-Zelande"),
        ("All Blacks XV", "NZL2", "Nouvelle-Zelande"),
        ("Angleterre A", "ENG2", "Angleterre"),
        ("Argentine", "ARG", "Argentine"),
        ("Argentine XV", "ARG2", "Argentine"),
        ("Australie", "AUS", "Australie"),
        ("Barbarians", "BAR", "Barbarians"),
        ("Canada", "CAN", "Canada"),
        ("Chili", "CHI", "Chili"),
        ("Espagne", "ESP", "Espagne"),
        ("Fidji", "FIJ", "Fidji"),
        ("France A", "FRA2", "France"),
        ("Galles", "WAL", "Galles"),
        ("Georgie", "GEO", "Georgie"),
        ("Hong Kong", "HKG", "Hong Kong"),
        ("Irlande A", "IRL2", "Irlande"),
        ("Italie XV", "ITA2", "Italie"),
        ("Japon", "JPN", "Japon"),
        ("Japon XV", "JPN2", "Japon"),
        ("Maori All Blacks", "MAO", "Nouvelle-Zelande"),
        ("Portugal", "POR", "Portugal"),
        ("Roumanie", "ROUM", "Roumanie"),
        ("Etats-Unis", "USA", "Etats-Unis"),
        ("Uruguay", "URU", "Uruguay"),
        ("Zimbabwe", "ZIM", "Zimbabwe"),
    ],
}

ERCC_LABELS = {
    "Clermont": "ASM",
    "Glasgow": "GLA",
    "Leicester": "LEIC",
    "Leinster": "LEI",
    "Pau": "PAU",
    "Sale": "SAL",
    "Connacht": "CON",
    "Exeter": "EXE",
    "La Rochelle": "LAR",
    "Lions": "LIO",
    "Saracens": "SAR",
    "Toulouse": "TOU",
    "Bordeaux": "UBB",
    "Bristol": "BRS",
    "Gloucester": "GLO",
    "Munster": "MUN",
    "Racing 92": "RAC",
    "Racing": "RAC",
    "Stormers": "STO",
    "Bath": "BAT",
    "Bulls": "BUL",
    "Cardiff": "CDF",
    "Montpellier": "MHR",
    "Northampton": "NOR",
    "Northamtp.": "NOR",
    "Paris": "SFP",
    "Stade Francais": "SFP",
}

ERCH_LABELS = {
    "Bayonne": "BAY",
    "Cheetahs": "CHE",
    "Dragons": "DRA",
    "Perpignan": "USAP",
    "Ulster": "ULS",
    "Zebre": "ZEB",
    "Castres": "CAS",
    "Lyon": "LOU",
    "Newcastle": "NEW",
    "Scarlets": "SCA",
    "Sharks": "SHA",
    "Trévise": "TRE",
    "Treviso": "TRE",
    "Black Lion": "BLA",
    "Edimbourg": "EDI",
    "Edinburgh": "EDI",
    "Harlequins": "HAR",
    "Ospreys": "OSP",
    "Toulon": "TOL",
    "Vannes": "VAN",
}

URC_LABELS = {
    "Bulls": "BUL",
    "Sharks": "SHA",
    "Stormers": "STO",
    "Glasgow": "GLA",
    "Edimbourg": "EDI",
    "Edinburgh": "EDI",
    "Cardiff": "CDF",
    "Lions": "LIO",
    "Dragons": "DRA",
    "Trévise": "TRE",
    "Treviso": "TRE",
    "Leinster": "LEI",
    "Ulster": "ULS",
    "Munster": "MUN",
    "Scarlets": "SCA",
    "Ospreys": "OSP",
    "Connacht": "CON",
    "Zebre": "ZEB",
}

PREM_LABELS = {
    "Northampton": "NOR",
    "Northamtp.": "NOR",
    "Gloucester": "GLO",
    "Bath": "BAT",
    "Bristol": "BRS",
    "Saracens": "SAR",
    "Leicester": "LEIC",
    "Exeter": "EXE",
    "Newcastle": "NEW",
    "Sale": "SAL",
    "Harlequins": "HAR",
}

INT_LABELS = {
    "Af. Sud": "RSA",
    "Af. Sud A": "RSA2",
    "All Blacks": "NZL",
    "All Blacks XV": "NZL2",
    "Angleterre A": "ENG2",
    "Argentine": "ARG",
    "Argentine XV": "ARG2",
    "Australie": "AUS",
    "Barbarians": "BAR",
    "Canada": "CAN",
    "Chili": "CHI",
    "Espagne": "ESP",
    "Fidji": "FIJ",
    "France A": "FRA2",
    "Galles": "WAL",
    "Georgie": "GEO",
    "Hong Kong": "HKG",
    "Irlande A": "IRL2",
    "Italie XV": "ITA2",
    "Japon": "JPN",
    "Japon XV": "JPN2",
    "Māori All B.": "MAO",
    "Maori All B.": "MAO",
    "Portugal": "POR",
    "Roumanie": "ROUM",
    "USA": "USA",
    "Uruguay": "URU",
    "Zimbabwe": "ZIM",
    "France": "FRA",
    "Angleterre": "ENG",
    "Ecosse": "SCO",
    "Irlande": "IRL",
    "Italie": "ITA",
    "Pays de Galles": "WAL",
}

LABELS_BY_CODE: dict[str, dict[str, str]] = {
    "ERCC": ERCC_LABELS,
    "ERCH": ERCH_LABELS,
    "URC": URC_LABELS,
    "PREM": PREM_LABELS,
    "INT": INT_LABELS,
}
