CLUBS = [
    ("TOP14", "TOU", "stade-toulousain", "transferts-stade-toulousain"),
    ("TOP14", "UBB", "union-bordeaux-begles", "transferts-union-bordeaux-begles"),
    ("TOP14", "RAC", "racing-92", "transferts-racing-92"),
    ("TOP14", "SFP", "stade-francais-paris", "transferts-stade-francais-paris"),
    ("TOP14", "TOL", "rugby-club-toulonnais", "transferts-rugby-club-toulonnais"),
    ("TOP14", "LAR", "la-rochelle", "transferts-la-rochelle"),
    ("TOP14", "ASM", "asm-clermont-auvergne", "transferts-asm-clermont-auvergne"),
    ("TOP14", "LOU", "lou", "transferts-lou"),
    ("TOP14", "MHR", "montpellier", "transferts-montpellier"),
    ("TOP14", "CAS", "castres-olympique", "transferts-castres-olympique"),
    ("TOP14", "PAU", "pau", "transferts-pau"),
    ("TOP14", "BAY", "aviron-bayonnais", "transferts-aviron-bayonnais"),
    ("TOP14", "USAP", "usap", "transferts-usap"),
    ("TOP14", "VAN", "rcvannes", "transferts-rcvannes"),
    ("PROD2", "BEZ", "asbh", "transferts-asbh"),
    ("PROD2", "OYO", "us-oyonnax-rugby", "transferts-us-oyonnax-rugby"),
    ("PROD2", "COL", "colomiers", "transferts-colomiers"),
    ("PROD2", "NEV", "uson-nevers-rugby", "transferts-uson-nevers-rugby"),
    ("PROD2", "AIX", "provence-rugby", "transferts-provence-rugby"),
    ("PROD2", "GRE", "grenoble-rugby", "transferts-grenoble-rugby"),
    ("PROD2", "BIA", "biarritz-olympique", "transferts-biarritz-olympique"),
    ("PROD2", "AGE", "agen", "transferts-agen"),
    ("PROD2", "BRI", "ca-brive-correze-limousin", "transferts-ca-brive-correze-limousin"),
    ("PROD2", "NIC", "stade-nicois", "transferts-stade-nicois"),
    ("PROD2", "ANG", "saxv", "transferts-saxv"),
    ("PROD2", "DAX", "us-dax-rugby-landes", "transferts-us-dax-rugby-landes"),
    ("PROD2", "NAR", "narbonne", "transferts-narbonne"),
    ("PROD2", "AUR", "aurillac", "transferts-aurillac"),
    ("PROD2", "MTB", "montauban", "transferts-montauban"),
    ("PROD2", "VAL", "valence-romans", "transferts-valence-romans"),
]

PARCOURS_KEYWORDS = {
    "TOU": ["Toulouse", "Stade Toulousain"],
    "UBB": ["Bordeaux", "Union Bordeaux"],
    "RAC": ["Racing 92", "Racing"],
    "SFP": ["Stade Français", "Paris"],
    "TOL": ["Toulon", "RC Toulon"],
    "LAR": ["Rochelle", "La Rochelle"],
    "ASM": ["Clermont", "ASM"],
    "LOU": ["Lyon", "LOU"],
    "MHR": ["Montpellier"],
    "CAS": ["Castres"],
    "PAU": ["Pau", "Section Paloise"],
    "BAY": ["Bayonne", "Aviron"],
    "USAP": ["Perpignan", "USAP"],
    "VAN": ["Vannes"],
    "BEZ": ["Béziers", "Beziers"],
    "OYO": ["Oyonnax"],
    "COL": ["Colomiers"],
    "NEV": ["Nevers"],
    "AIX": ["Provence", "Aix"],
    "GRE": ["Grenoble"],
    "BIA": ["Biarritz"],
    "AGE": ["Agen"],
    "BRI": ["Brive"],
    "NIC": ["Nice", "Niçois", "Nicois"],
    "ANG": ["Angoulême", "Angouleme", "Soyaux"],
    "DAX": ["Dax"],
    "NAR": ["Narbonne"],
    "AUR": ["Aurillac"],
    "MTB": ["Montauban"],
    "VAL": ["Valence"],
}

ALL_RUGBY_LABEL_TO_SHORT = {
    "Stade Toulousain": "TOU",
    "Toulouse": "TOU",
    "Union Bordeaux": "UBB",
    "Bordeaux": "UBB",
    "Racing 92": "RAC",
    "Stade Français": "SFP",
    "Paris": "SFP",
    "Toulon": "TOL",
    "RC Toulon": "TOL",
    "La Rochelle": "LAR",
    "Rochelle": "LAR",
    "Clermont": "ASM",
    "ASM": "ASM",
    "Lyon": "LOU",
    "LOU": "LOU",
    "Montpellier": "MHR",
    "Castres": "CAS",
    "Pau": "PAU",
    "Bayonne": "BAY",
    "Aviron": "BAY",
    "Perpignan": "USAP",
    "USAP": "USAP",
    "Vannes": "VAN",
    "Béziers": "BEZ",
    "Beziers": "BEZ",
    "Oyonnax": "OYO",
    "Colomiers": "COL",
    "Nevers": "NEV",
    "Provence": "AIX",
    "Aix": "AIX",
    "Grenoble": "GRE",
    "Biarritz": "BIA",
    "Agen": "AGE",
    "Brive": "BRI",
    "Nice": "NIC",
    "Niçois": "NIC",
    "Angoulême": "ANG",
    "Angouleme": "ANG",
    "Soyaux": "ANG",
    "Dax": "DAX",
    "Narbonne": "NAR",
    "Aurillac": "AUR",
    "Montauban": "MTB",
    "Valence Romans": "VAL",
    "Valence": "VAL",
}
