CLUBS = [
    ("TOP14", "TOU", "stade-toulousain", "transferts-stade-toulousain"),
    ("TOP14", "UBB", "union-bordeaux-begles", "transferts-union-bordeaux-begles"),
    ("TOP14", "RAC", "racing-92", "transferts-racing-92"),
    ("TOP14", "SFP", "stade-francais-paris", "transferts-stade-francais-paris"),
    ("TOP14", "TOL", "rugby-club-toulonnais", "transferts-rugby-club-toulonnais"),
    ("TOP14", "LAR", "la-rochelle", "transferts-la-rochelle"),
    ("TOP14", "ASM", "asm-clermont-auvergne", "transferts-asm-clermont-auvergne"),
    ("TOP14", "LOU", "lou", "transferts-lou"),
    ("TOP14", "MHR", "montpellier", "transferts-montpellier"),
    ("TOP14", "CAS", "castres-olympique", "transferts-castres-olympique"),
    ("TOP14", "PAU", "pau", "transferts-pau"),
    ("TOP14", "BAY", "aviron-bayonnais", "transferts-aviron-bayonnais"),
    ("TOP14", "USAP", "usap", "transferts-usap"),
    ("TOP14", "VAN", "rcvannes", "transferts-rcvannes"),
    ("PROD2", "BEZ", "asbh", "transferts-asbh"),
    ("PROD2", "OYO", "us-oyonnax-rugby", "transferts-us-oyonnax-rugby"),
    ("PROD2", "COL", "colomiers", "transferts-colomiers"),
    ("PROD2", "NEV", "uson-nevers-rugby", "transferts-uson-nevers-rugby"),
    ("PROD2", "AIX", "provence-rugby", "transferts-provence-rugby"),
    ("PROD2", "GRE", "grenoble-rugby", "transferts-grenoble-rugby"),
    ("PROD2", "BIA", "biarritz-olympique", "transferts-biarritz-olympique"),
    ("PROD2", "AGE", "agen", "transferts-agen"),
    ("PROD2", "BRI", "ca-brive-correze-limousin", "transferts-ca-brive-correze-limousin"),
    ("PROD2", "NIC", "stade-nicois", "transferts-stade-nicois"),
    ("PROD2", "ANG", "saxv", "transferts-saxv"),
    ("PROD2", "DAX", "us-dax-rugby-landes", "transferts-us-dax-rugby-landes"),
    ("PROD2", "NAR", "narbonne", "transferts-narbonne"),
    ("PROD2", "AUR", "aurillac", "transferts-aurillac"),
    ("PROD2", "MTB", "montauban", "transferts-montauban"),
    ("PROD2", "VAL", "valence-romans", "transferts-valence-romans"),
    ("NAT", "MAS", "massy", "transferts-massy"),
    ("NAT", "CAR", "carcassonne", "transferts-carcassonne"),
    ("NAT", "ALB", "albi", "transferts-albi"),
    ("NAT", "MDM", "mont-de-marsan", "transferts-mont-de-marsan"),
    ("NAT", "CHA", "chambery", "transferts-chambery"),
    ("NAT", "ROU", "rouen", "transferts-rouen"),
    ("NAT", "SUR", "suresnes", "transferts-suresnes"),
    ("NAT", "BOU", "bourgoin", "transferts-bourgoin"),
    ("NAT", "ORL", "orleans", "transferts-orleans"),
    ("NAT", "PER", "perigueux", "transferts-perigueux"),
    ("NAT", "REN", "rennes", "transferts-rennes"),
    ("NAT", "VIE", "vienne", "transferts-vienne"),
    ("NAT", "USB", "bourg-en-bresse", "transferts-bourg-en-bresse"),
    ("NAT", "MAR", "marcq-en-baroeul", "transferts-marcq-en-baroeul"),
    ("PREM", "NOR", "northampton", "transferts-northampton"),
    ("PREM", "GLO", "gloucester", "transferts-gloucester"),
    ("PREM", "BAT", "bath", "transferts-bath"),
    ("PREM", "BRS", "bristol", "transferts-bristol"),
    ("PREM", "SAR", "saracens", "transferts-saracens"),
    ("PREM", "LEIC", "leicester", "transferts-leicester"),
    ("PREM", "EXE", "exeter", "transferts-exeter"),
    ("PREM", "NEW", "newcastle", "transferts-newcastle"),
    ("PREM", "SAL", "sale", "transferts-sale"),
    ("PREM", "HAR", "harlequins", "transferts-harlequins"),
    ("URC", "BUL", "bulls", "transferts-bulls"),
    ("URC", "SHA", "sharks", "transferts-sharks"),
    ("URC", "STO", "stormers", "transferts-stormers"),
    ("URC", "GLA", "glasgow", "transferts-glasgow"),
    ("URC", "EDI", "edinburgh", "transferts-edinburgh"),
    ("URC", "CDF", "cardiff", "transferts-cardiff"),
    ("URC", "LIO", "lions", "transferts-lions"),
    ("URC", "DRA", "dragons", "transferts-dragons"),
    ("URC", "TRE", "benetton", "transferts-benetton"),
    ("URC", "LEI", "leinster", "transferts-leinster"),
    ("URC", "ULS", "ulster", "transferts-ulster"),
    ("URC", "MUN", "munster", "transferts-munster"),
    ("URC", "SCA", "scarlets", "transferts-scarlets"),
    ("URC", "OSP", "ospreys", "transferts-ospreys"),
    ("URC", "CON", "connacht", "transferts-connacht"),
    ("URC", "ZEB", "zebre", "transferts-zebre"),
]

PARCOURS_KEYWORDS = {
    "TOU": ["Toulouse", "Stade Toulousain"],
    "UBB": ["Bordeaux", "Union Bordeaux"],
    "RAC": ["Racing 92", "Racing"],
    "SFP": ["Stade Français", "Paris"],
    "TOL": ["Toulon", "RC Toulon"],
    "LAR": ["Rochelle", "La Rochelle"],
    "ASM": ["Clermont", "ASM"],
    "LOU": ["Lyon", "LOU"],
    "MHR": ["Montpellier"],
    "CAS": ["Castres"],
    "PAU": ["Pau", "Section Paloise"],
    "BAY": ["Bayonne", "Aviron"],
    "USAP": ["Perpignan", "USAP"],
    "VAN": ["Vannes"],
    "BEZ": ["Béziers", "Beziers"],
    "OYO": ["Oyonnax"],
    "COL": ["Colomiers"],
    "NEV": ["Nevers"],
    "AIX": ["Provence", "Aix"],
    "GRE": ["Grenoble"],
    "BIA": ["Biarritz"],
    "AGE": ["Agen"],
    "BRI": ["Brive"],
    "NIC": ["Nice", "Niçois", "Nicois"],
    "ANG": ["Angoulême", "Angouleme", "Soyaux"],
    "DAX": ["Dax"],
    "NAR": ["Narbonne"],
    "AUR": ["Aurillac"],
    "MTB": ["Montauban"],
    "VAL": ["Valence"],
}

ALL_RUGBY_LABEL_TO_SHORT = {
    "Stade Toulousain": "TOU",
    "Toulouse": "TOU",
    "Union Bordeaux": "UBB",
    "Union Bordeaux Bègles": "UBB",
    "Bordeaux": "UBB",
    "Racing 92": "RAC",
    "Stade Français": "SFP",
    "Paris": "SFP",
    "Toulon": "TOL",
    "RC Toulon": "TOL",
    "Rugby Club Toulonnais": "TOL",
    "La Rochelle": "LAR",
    "Stade Rochelais": "LAR",
    "Rochelle": "LAR",
    "Clermont": "ASM",
    "ASM": "ASM",
    "ASM Clermont": "ASM",
    "Lyon": "LOU",
    "LOU": "LOU",
    "Lyon OU": "LOU",
    "Lyon OU Rugby": "LOU",
    "Montpellier": "MHR",
    "Montpellier HR": "MHR",
    "Montpellier Hérault Rugby": "MHR",
    "Castres": "CAS",
    "Castres Olympique": "CAS",
    "Pau": "PAU",
    "Section Paloise": "PAU",
    "Bayonne": "BAY",
    "Aviron": "BAY",
    "Aviron Bayonnais": "BAY",
    "Perpignan": "USAP",
    "USAP": "USAP",
    "Vannes": "VAN",
    "RC Vannes": "VAN",
    "Béziers": "BEZ",
    "Beziers": "BEZ",
    "Oyonnax": "OYO",
    "Colomiers": "COL",
    "Nevers": "NEV",
    "Provence": "AIX",
    "Aix": "AIX",
    "Grenoble": "GRE",
    "FC Grenoble": "GRE",
    "Biarritz": "BIA",
    "Biarritz Olympique": "BIA",
    "Agen": "AGE",
    "Brive": "BRI",
    "Nice": "NIC",
    "Niçois": "NIC",
    "Angoulême": "ANG",
    "Angouleme": "ANG",
    "Soyaux": "ANG",
    "Dax": "DAX",
    "Narbonne": "NAR",
    "Aurillac": "AUR",
    "Montauban": "MTB",
    "Valence Romans": "VAL",
    "Valence": "VAL",
}

SHORT_TO_COMPETITION = {short: code for code, short, *_ in CLUBS}
