spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/ovalytics
    username: aymteb
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

ovalytics:
  import:
    file: